### ISSUE TITLE
oneTBB documented decision making

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#102]
Define processes for decision making within the oneTBB project. This should include a RFC process for new design and feature proposals
(see oneDNN for example - PR tagged RFC that links to the proposal on the GitHub wiki).

Acceptance Criteria:
Decision making process published in the repository and reviewed by the community

**Comment by vbm23** [comment]
@pavelkumbrasev Projects have initiated describing the RFC Process with Template in their respective projects and would be nice if all projects can align in the naming convention and then can always continually improve to include things that do not fit right now
https://github.com/oneapi-src/oneCCL/tree/rfcs
https://github.com/oneapi-src/oneDNN/tree/rfcs

**Comment by vbm23** [comment]
@pavelkumbrasev I suppose it depends on what works for the team, though separate branch was thought so as to avoid confusion over RFCs in Release Branches and otherwise. 
Hence, if the project branching mechanism have good oversight by respective roles, then can work for now, else can always continually improve to have it separate based on how it goes.

**Comment by vbm23** [comment]
https://github.com/oneapi-src/oneTBB/pull/1464 Merged
