### ISSUE TITLE
oneMKL regular release cadence

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#37]
The project will make regular releases for the open source repo. Currently there is a gap between 2020 and 2023, a plan will be made to make regular binaries available.

Acceptance Criteria:
- A release schedule plan is published on the repo

**Comment by itopinsk** [comment]
@vbm23 we currently have regular releases since December last year. they now aligned with oneAPI release because the oneMKL backend version should be changed once a new release is available to public. In which form the schedule plan should be published on the repo? I don't see similar plan for other libraries most likely because they have no gap between releases in the past.

**Comment by rodburns** [comment]
Thanks for the information. It looks like you have a regular cadence for releases so this meets the criteria of the issue. In the future we might talk about roadmaps and scheduling, but for now this is good. Closing as done.

**Comment by itopinsk** [comment]
thanks!
