### ISSUE TITLE
oneDPL use of Slack channel

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#6]
- Link to the UXL Foundation Slack workspace and channel from the project README
- Assign team member(s) to monitor the Slack channel
- Set up notifications in the oneDPL Slack channel when new RFCs are added to the project repo for community review and comment

Acceptance Criteria:

- Link to Slack available on README
- Named team member(s) monitoring channel
- Notifications appearing on the Slack channel when new RFCs are added to the project

**Comment by vbm23** [comment]
Awaiting PR to be created by @rscohn2

**Comment by vbm23** [comment]
@timmiesmith  https://github.com/oneapi-src/oneDPL/pull/1584 created by @rscohn2 would help meet the third acceptance criteria.

In order to meet the remaining acceptance criterias, can you help update links to UXL Foundation Slack Workspace and [oneDPL channel](https://app.slack.com/client/T06EGKQ30NM/C06HLTMF8QK) in relevant sections of README as [CONTRIBUTING.md](CONTRIBUTING.md) and/or Support and Contribution if applicable.

So also, Team members involved into working with external contributors would need to monitor the channel. 

Thanks!!

**Comment by timmiesmith** [comment]
PR to add the link to the slack channel is up for review. @danhoeflinger and @timmiesmith will be the oneDPL team members monitoring the slack channel.
